### ISSUE TITLE
Merging existing MSFS scenery and other functions just throw errors

### ISSUE THREAD

**Issue by HexHyte** [Thalixte/Google-Earth-Decoder-Optimization-Tools#11]
When clicking on Merge an existing MSFS Scenery and some other functions, I encounter errors like the following:

```
bpy.ops.wm.merge_sceneries_panel()
Python: Traceback (most recent call last):
  File "C:\Users\HexHyte\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Google-Earth-Decoder-Optimization-Tools\UI\operator\panel.py", line 35, in invoke
    self.__save_operator_context(context, event)
  File "C:\Users\HexHyte\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Google-Earth-Decoder-Optimization-Tools\UI\operator\panel.py", line 48, in __save_operator_context
    panel_props.setting_sections = self.starting_section
TypeError: bpy_struct: item.attr = val: enum "MERGE" not found in ('PROJECT', 'AUTOMATIC_BUILD')
```

**Comment by HexHyte** [comment]
Oh sorry it's a duplicate of #5
