### ISSUE TITLE
Python: Traceback Error

### ISSUE THREAD

**Issue by AppleUK123** [Thalixte/Google-Earth-Decoder-Optimization-Tools#5]
Hi Thaxilite, thank you so much for this wonderful addon.

I'm getting into PG Creation and had no problem initialising the folders and optimising the project.
However, when I try and click the 3.Create the terraform.... option it shows an error.

Any help would be appreciated, thank you 👍
![8023A0EA-8E8E-49E5-9ACE-3699FC939708_1_102_o](https://github.com/Thalixte/Google-Earth-Decoder-Optimization-Tools/assets/101504298/2d25ae01-a841-4efc-a391-10d216c04418)

**Comment by Ati108** [comment]
Hi, I have the same problem. I can´t open merge, 3D clean up. I tried to reinstall addon, but still the same error message. Thanks
![error](https://github.com/Thalixte/Google-Earth-Decoder-Optimization-Tools/assets/162547160/59c56403-326c-43de-86dc-0f363f3537f5)

**Comment by LowflyerDE** [comment]
Hi Thaxilite,

thank you for your great GEDOT tool. I sent you a small donation for it because I think it's great that you offer the tool for free. But I have the exact same Python: Traceback Error as AppleUK123 and Ati108. It affects not only the merge function and the create the terraform and exclusioon polygons for the scenery, but also the functions cleanup 3d data from google earth tiles,  generate height data based on google earth tiles, all functions in the geocode tools folder and most of the functions in the other tools folder. The problem occurs with all versions from version 2.00 onwards. I am using Blender 3.51.
Since it seems to work for others, I assume a problem with the installation or configuration. Would you have some troubleshooting advice?

Thanks a lot

**Comment by Thalixte** [comment]
Hello. Can you check if you have this section on your project ini file ?

[OPENSTREETMAP]
airport_city =
high_precision = False
exclude_ground = True
exclude_water = True
exclude_forests = True
exclude_woods = True
exclude_nature_reserves = True
exclude_parks = True
isolate_3d_data = False
keep_buildings = True
keep_roads = True
keep_constructions = True
force_osm_data_download = False
keep_residential = False
process_all = False
ground_exclusion_margin = 0.0
create_forests_vegetation = False
create_woods_vegetation = False
building_margin = 8

If not, add it.

Best regards,

**Comment by LowflyerDE** [comment]
Hi Thalixte,

thanks for your answer. The project.ini file have all the entrys. I also don't think it's due to missing entries in the project.ini file, because the traceback error is displayed as soon as I click on the menu item from the GEDOT menu in Blender and before the configuration window for the function opens, in which I can then select the project. So if I click on

-> "(Optional) Merge an existing MSFS Scenery project into another", i get this error massage instead the configuration window:
![Merge](https://github.com/Thalixte/Google-Earth-Decoder-Optimization-Tools/assets/165132187/cc023a6e-2dae-4615-8d8a-ce3525b8b20e)

->  "create the terraform and exclusioon polygons for the scenery", i get this error massage instead the configuration window:
![terraform](https://github.com/Thalixte/Google-Earth-Decoder-Optimization-Tools/assets/165132187/905ccf17-e8e7-45a2-bf88-38e9760f3272)

-> "cleanup 3d data from google earth tiles", i get this error massage instead the configuration window:
![cleanup](https://github.com/Thalixte/Google-Earth-Decoder-Optimization-Tools/assets/165132187/462ec6fe-e9f9-4bf2-be89-f9c3bc03e0fe)

-> "generate height data based on google earth tiles", i get this error massage instead the configuration window:
![height](https://github.com/Thalixte/Google-Earth-Decoder-Optimization-Tools/assets/165132187/dbf30bec-3085-4039-a7d8-e428304e318e)

-> one of the options from the Geocode submenu, i get this error massage instead the configuration window:
![geocode](https://github.com/Thalixte/Google-Earth-Decoder-Optimization-Tools/assets/165132187/dd5a278e-7035-4d16-94eb-3d4cae0266bb)

And it seems that even when optimising a project, the option to bake the textures does not work. when i optimise a project with this option, the number of texture files is the same as before. If I optimise the same project with GEDOT version 1.13, the number of texture files is reduced, as should be the case when baking. however, no errors are displayed during the optimisation process with version 2.0.6. i use Lily texture packer version 1.2.3 64 bit.
I hope you can narrow down the problem better with this information.

Best regards

**Comment by Thalixte** [comment]
Here is a working .ini file:
```
[PROJECT]
output_texture_format = png
collider_as_lower_lod = False

[MERGE]
project_path_to_merge = 
definition_file_to_merge = 

[TILE]
lat_correction = 0
lon_correction = 0

[LODS]
target_min_size_values = 0, 15, 50, 70, 80, 90, 100

[OPENSTREETMAP]
airport_city = 
high_precision = False
exclude_ground = True
exclude_water = True
exclude_forests = True
exclude_woods = True
exclude_nature_reserves = True
exclude_parks = True
isolate_3d_data = True
keep_buildings = True
keep_roads = True
keep_constructions = True
force_osm_data_download = False
keep_residential_and_industrial = False
process_all = False
ground_exclusion_margin = 10
create_forests_vegetation = False
create_woods_vegetation = False

[GEOCODE]
geocode = Promenade des anglais, Nice
geocode_margin = 5.0
preserve_roads = False
preserve_buildings = False
landmark_type = POI
landmark_offset = 0
add_lights = False

[ALTITUDE_ADJUSTMENT]
altitude_adjustment = 0

[AUTOMATIC_BUILD]
build_package_enabled = True

[BACKUP]
backup_enabled = True

[HEIGHT_MAPS]
height_adjustment = -1

[TEXTURES]
resize_ratio = 0.5
red_level = 1
green_level = 0.95
blue_level = 0.9
brightness = 0.85
contrast = 0.9
saturation = 0.95
hue = 0
```

**Comment by HexHyte** [comment]
**What is the correct `.ini` file to edit?**

Editing `project_settings.ini` under `C:\Users\HexHyte\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Google-Earth-Decoder-Optimization-Tools\resource\config` doesn't make a difference and continues to throw the following error (or similar) when selecting the merge tool or other tools:

```python
Python: Traceback (most recent call last):
  File "C:\Users\HexHyte\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Google-Earth-Decoder-Optimization-Tools\UI\operator\panel.py", line 35, in invoke
    self.__save_operator_context(context, event)
  File "C:\Users\HexHyte\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Google-Earth-Decoder-Optimization-Tools\UI\operator\panel.py", line 48, in __save_operator_context
    panel_props.setting_sections = self.starting_section
TypeError: bpy_struct: item.attr = val: enum "MERGE" not found in ('PROJECT', 'AUTOMATIC_BUILD')
```

**Comment by Sumsar3** [comment]
> **What is the correct `.ini` file to edit?**
> 
> Editing `project_settings.ini` under `C:\Users\HexHyte\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Google-Earth-Decoder-Optimization-Tools\resource\config` doesn't make a difference and continues to throw the following error (or similar) when selecting the merge tool or other tools:
> 
> ```python
> Python: Traceback (most recent call last):
>   File "C:\Users\HexHyte\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Google-Earth-Decoder-Optimization-Tools\UI\operator\panel.py", line 35, in invoke
>     self.__save_operator_context(context, event)
>   File "C:\Users\HexHyte\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Google-Earth-Decoder-Optimization-Tools\UI\operator\panel.py", line 48, in __save_operator_context
>     panel_props.setting_sections = self.starting_section
> TypeError: bpy_struct: item.attr = val: enum "MERGE" not found in ('PROJECT', 'AUTOMATIC_BUILD')
> ```

Same problem here on October 2024. Editing project ini with the "working values" doesn't work. I can't use half of the addon's functions because it gives the same error.
